### ISSUE TITLE
error with ip2sl and hass .37.1

### ISSUE THREAD

**Issue by bbrendon** [tinglis1/home-assistant-custom#1]
It appears something is up... not sure what is wrong.

```
17-02-07 18:27:36 INFO (MainThread) [homeassistant.bootstrap] Setting up frontend
17-02-07 18:27:36 INFO (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=frontend>
17-02-07 18:27:36 INFO (MainThread) [homeassistant.loader] Loaded notify.ip2sl from custom_components.notify.ip2sl
17-02-07 18:27:36 INFO (MainThread) [homeassistant.bootstrap] Setting up notify
17-02-07 18:27:36 INFO (MainThread) [homeassistant.components.notify] Setting up notify.ip2sl
17-02-07 18:27:36 ERROR (MainThread) [homeassistant.components.notify] Error setting up platform ip2sl
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/notify/__init__.py", line 101, in async_setup_platform
    None, platform.get_service, hass, p_config, discovery_info)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: get_service() takes 2 positional arguments but 3 were given

```

**Comment by bbrendon** [comment]
hA! I found the fix in the forums.
https://community.home-assistant.io/t/support-for-ip-ir-bridges/3480

`def get_service(hass, config, discovery_info):`
`#def get_service(hass, config):`
